// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: packet_analysis.proto
#ifndef GRPC_packet_5fanalysis_2eproto__INCLUDED
#define GRPC_packet_5fanalysis_2eproto__INCLUDED

#include "packet_analysis.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace packet {

// Service
class PacketAnalysisService final {
 public:
  static constexpr char const* service_full_name() {
    return "packet.PacketAnalysisService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::packet::PacketWindow>> StreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::packet::PacketWindow>>(StreamWindowRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::packet::PacketWindow>> AsyncStreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::packet::PacketWindow>>(AsyncStreamWindowRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::packet::PacketWindow>> PrepareAsyncStreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::packet::PacketWindow>>(PrepareAsyncStreamWindowRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::ClientWriteReactor< ::packet::PacketWindow>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::packet::PacketWindow>* StreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::packet::PacketWindow>* AsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::packet::PacketWindow>* PrepareAsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::packet::PacketWindow>> StreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::packet::PacketWindow>>(StreamWindowRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::packet::PacketWindow>> AsyncStreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::packet::PacketWindow>>(AsyncStreamWindowRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::packet::PacketWindow>> PrepareAsyncStreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::packet::PacketWindow>>(PrepareAsyncStreamWindowRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::ClientWriteReactor< ::packet::PacketWindow>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::packet::PacketWindow>* StreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response) override;
    ::grpc::ClientAsyncWriter< ::packet::PacketWindow>* AsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::packet::PacketWindow>* PrepareAsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamWindow_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamWindow(::grpc::ServerContext* context, ::grpc::ServerReader< ::packet::PacketWindow>* reader, ::packet::AnalysisAck* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamWindow() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamWindow(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::packet::PacketWindow>* /*reader*/, ::packet::AnalysisAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamWindow(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::packet::AnalysisAck, ::packet::PacketWindow>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamWindow<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamWindow() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::packet::PacketWindow, ::packet::AnalysisAck>(
            [this](
                   ::grpc::CallbackServerContext* context, ::packet::AnalysisAck* response) { return this->StreamWindow(context, response); }));
    }
    ~WithCallbackMethod_StreamWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamWindow(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::packet::PacketWindow>* /*reader*/, ::packet::AnalysisAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::packet::PacketWindow>* StreamWindow(
      ::grpc::CallbackServerContext* /*context*/, ::packet::AnalysisAck* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamWindow<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamWindow() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamWindow(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::packet::PacketWindow>* /*reader*/, ::packet::AnalysisAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamWindow() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamWindow(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::packet::PacketWindow>* /*reader*/, ::packet::AnalysisAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamWindow(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamWindow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamWindow() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->StreamWindow(context, response); }));
    }
    ~WithRawCallbackMethod_StreamWindow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamWindow(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::packet::PacketWindow>* /*reader*/, ::packet::AnalysisAck* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* StreamWindow(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

class PacketAnalyzer final {
 public:
  static constexpr char const* service_full_name() {
    return "packet.PacketAnalyzer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::packet::EventBatch* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::packet::EventBatch>> AsyncGetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::packet::EventBatch>>(AsyncGetEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::packet::EventBatch>> PrepareAsyncGetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::packet::EventBatch>>(PrepareAsyncGetEventsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::packet::EventBatch>* AsyncGetEventsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::packet::EventBatch>* PrepareAsyncGetEventsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::packet::EventBatch* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::packet::EventBatch>> AsyncGetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::packet::EventBatch>>(AsyncGetEventsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::packet::EventBatch>> PrepareAsyncGetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::packet::EventBatch>>(PrepareAsyncGetEventsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response, std::function<void(::grpc::Status)>) override;
      void GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::packet::EventBatch>* AsyncGetEventsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::packet::EventBatch>* PrepareAsyncGetEventsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetEvents_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetEvents(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetEvents() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEvents(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::packet::EventBatch* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEvents(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::packet::EventBatch>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetEvents<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetEvents() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::packet::EventBatch>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response) { return this->GetEvents(context, request, response); }));}
    void SetMessageAllocatorFor_GetEvents(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::packet::EventBatch>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::packet::EventBatch>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEvents(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::packet::EventBatch* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::packet::EventBatch* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetEvents<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetEvents() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEvents(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::packet::EventBatch* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetEvents() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEvents(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::packet::EventBatch* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEvents(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetEvents() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetEvents(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEvents(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::packet::EventBatch* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEvents(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetEvents : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetEvents() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::packet::EventBatch>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::packet::EventBatch>* streamer) {
                       return this->StreamedGetEvents(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetEvents() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetEvents(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::packet::EventBatch* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetEvents(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::packet::EventBatch>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetEvents<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetEvents<Service > StreamedService;
};

}  // namespace packet


#endif  // GRPC_packet_5fanalysis_2eproto__INCLUDED
