// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_analysis.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_packet_5fanalysis_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_packet_5fanalysis_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_packet_5fanalysis_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_5fanalysis_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_packet_5fanalysis_2eproto;
namespace packet {
class AnalysisAck;
struct AnalysisAckDefaultTypeInternal;
extern AnalysisAckDefaultTypeInternal _AnalysisAck_default_instance_;
class EventBatch;
struct EventBatchDefaultTypeInternal;
extern EventBatchDefaultTypeInternal _EventBatch_default_instance_;
class HttpSession;
struct HttpSessionDefaultTypeInternal;
extern HttpSessionDefaultTypeInternal _HttpSession_default_instance_;
class PacketEvent;
struct PacketEventDefaultTypeInternal;
extern PacketEventDefaultTypeInternal _PacketEvent_default_instance_;
class PacketWindow;
struct PacketWindowDefaultTypeInternal;
extern PacketWindowDefaultTypeInternal _PacketWindow_default_instance_;
class TcpMeta;
struct TcpMetaDefaultTypeInternal;
extern TcpMetaDefaultTypeInternal _TcpMeta_default_instance_;
}  // namespace packet
PROTOBUF_NAMESPACE_OPEN
template<> ::packet::AnalysisAck* Arena::CreateMaybeMessage<::packet::AnalysisAck>(Arena*);
template<> ::packet::EventBatch* Arena::CreateMaybeMessage<::packet::EventBatch>(Arena*);
template<> ::packet::HttpSession* Arena::CreateMaybeMessage<::packet::HttpSession>(Arena*);
template<> ::packet::PacketEvent* Arena::CreateMaybeMessage<::packet::PacketEvent>(Arena*);
template<> ::packet::PacketWindow* Arena::CreateMaybeMessage<::packet::PacketWindow>(Arena*);
template<> ::packet::TcpMeta* Arena::CreateMaybeMessage<::packet::TcpMeta>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace packet {

// ===================================================================

class PacketWindow final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:packet.PacketWindow) */ {
 public:
  inline PacketWindow() : PacketWindow(nullptr) {}
  ~PacketWindow() override;
  explicit PROTOBUF_CONSTEXPR PacketWindow(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PacketWindow(const PacketWindow& from);
  PacketWindow(PacketWindow&& from) noexcept
    : PacketWindow() {
    *this = ::std::move(from);
  }

  inline PacketWindow& operator=(const PacketWindow& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketWindow& operator=(PacketWindow&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PacketWindow& default_instance() {
    return *internal_default_instance();
  }
  static inline const PacketWindow* internal_default_instance() {
    return reinterpret_cast<const PacketWindow*>(
               &_PacketWindow_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PacketWindow& a, PacketWindow& b) {
    a.Swap(&b);
  }
  inline void Swap(PacketWindow* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketWindow* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PacketWindow* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PacketWindow>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PacketWindow& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PacketWindow& from) {
    PacketWindow::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PacketWindow* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "packet.PacketWindow";
  }
  protected:
  explicit PacketWindow(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHttpSessionsFieldNumber = 4,
    kWindowStartFieldNumber = 1,
    kWindowEndFieldNumber = 2,
    kUserIdFieldNumber = 3,
  };
  // repeated .packet.HttpSession http_sessions = 4;
  int http_sessions_size() const;
  private:
  int _internal_http_sessions_size() const;
  public:
  void clear_http_sessions();
  ::packet::HttpSession* mutable_http_sessions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::HttpSession >*
      mutable_http_sessions();
  private:
  const ::packet::HttpSession& _internal_http_sessions(int index) const;
  ::packet::HttpSession* _internal_add_http_sessions();
  public:
  const ::packet::HttpSession& http_sessions(int index) const;
  ::packet::HttpSession* add_http_sessions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::HttpSession >&
      http_sessions() const;

  // int64 window_start = 1;
  void clear_window_start();
  int64_t window_start() const;
  void set_window_start(int64_t value);
  private:
  int64_t _internal_window_start() const;
  void _internal_set_window_start(int64_t value);
  public:

  // int64 window_end = 2;
  void clear_window_end();
  int64_t window_end() const;
  void set_window_end(int64_t value);
  private:
  int64_t _internal_window_end() const;
  void _internal_set_window_end(int64_t value);
  public:

  // int64 user_id = 3;
  void clear_user_id();
  int64_t user_id() const;
  void set_user_id(int64_t value);
  private:
  int64_t _internal_user_id() const;
  void _internal_set_user_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:packet.PacketWindow)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::HttpSession > http_sessions_;
    int64_t window_start_;
    int64_t window_end_;
    int64_t user_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fanalysis_2eproto;
};
// -------------------------------------------------------------------

class HttpSession final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:packet.HttpSession) */ {
 public:
  inline HttpSession() : HttpSession(nullptr) {}
  ~HttpSession() override;
  explicit PROTOBUF_CONSTEXPR HttpSession(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HttpSession(const HttpSession& from);
  HttpSession(HttpSession&& from) noexcept
    : HttpSession() {
    *this = ::std::move(from);
  }

  inline HttpSession& operator=(const HttpSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline HttpSession& operator=(HttpSession&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HttpSession& default_instance() {
    return *internal_default_instance();
  }
  static inline const HttpSession* internal_default_instance() {
    return reinterpret_cast<const HttpSession*>(
               &_HttpSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HttpSession& a, HttpSession& b) {
    a.Swap(&b);
  }
  inline void Swap(HttpSession* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HttpSession* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HttpSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HttpSession>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HttpSession& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HttpSession& from) {
    HttpSession::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HttpSession* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "packet.HttpSession";
  }
  protected:
  explicit HttpSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTcpPacketsFieldNumber = 4,
    kMethodFieldNumber = 1,
    kProtocolFieldNumber = 2,
    kUriFieldNumber = 3,
  };
  // repeated .packet.TcpMeta tcp_packets = 4;
  int tcp_packets_size() const;
  private:
  int _internal_tcp_packets_size() const;
  public:
  void clear_tcp_packets();
  ::packet::TcpMeta* mutable_tcp_packets(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::TcpMeta >*
      mutable_tcp_packets();
  private:
  const ::packet::TcpMeta& _internal_tcp_packets(int index) const;
  ::packet::TcpMeta* _internal_add_tcp_packets();
  public:
  const ::packet::TcpMeta& tcp_packets(int index) const;
  ::packet::TcpMeta* add_tcp_packets();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::TcpMeta >&
      tcp_packets() const;

  // string method = 1;
  void clear_method();
  const std::string& method() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_method(ArgT0&& arg0, ArgT... args);
  std::string* mutable_method();
  PROTOBUF_NODISCARD std::string* release_method();
  void set_allocated_method(std::string* method);
  private:
  const std::string& _internal_method() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method(const std::string& value);
  std::string* _internal_mutable_method();
  public:

  // string protocol = 2;
  void clear_protocol();
  const std::string& protocol() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_protocol(ArgT0&& arg0, ArgT... args);
  std::string* mutable_protocol();
  PROTOBUF_NODISCARD std::string* release_protocol();
  void set_allocated_protocol(std::string* protocol);
  private:
  const std::string& _internal_protocol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_protocol(const std::string& value);
  std::string* _internal_mutable_protocol();
  public:

  // string uri = 3;
  void clear_uri();
  const std::string& uri() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uri(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uri();
  PROTOBUF_NODISCARD std::string* release_uri();
  void set_allocated_uri(std::string* uri);
  private:
  const std::string& _internal_uri() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uri(const std::string& value);
  std::string* _internal_mutable_uri();
  public:

  // @@protoc_insertion_point(class_scope:packet.HttpSession)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::TcpMeta > tcp_packets_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protocol_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uri_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fanalysis_2eproto;
};
// -------------------------------------------------------------------

class TcpMeta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:packet.TcpMeta) */ {
 public:
  inline TcpMeta() : TcpMeta(nullptr) {}
  ~TcpMeta() override;
  explicit PROTOBUF_CONSTEXPR TcpMeta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TcpMeta(const TcpMeta& from);
  TcpMeta(TcpMeta&& from) noexcept
    : TcpMeta() {
    *this = ::std::move(from);
  }

  inline TcpMeta& operator=(const TcpMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline TcpMeta& operator=(TcpMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TcpMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const TcpMeta* internal_default_instance() {
    return reinterpret_cast<const TcpMeta*>(
               &_TcpMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TcpMeta& a, TcpMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(TcpMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TcpMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TcpMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TcpMeta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TcpMeta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TcpMeta& from) {
    TcpMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TcpMeta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "packet.TcpMeta";
  }
  protected:
  explicit TcpMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLocalAddressFieldNumber = 1,
    kRemoteAddressFieldNumber = 2,
    kLocalPortFieldNumber = 3,
    kRemotePortFieldNumber = 4,
    kSequenceNumberFieldNumber = 5,
    kFlagFieldNumber = 6,
  };
  // string local_address = 1;
  void clear_local_address();
  const std::string& local_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_local_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_local_address();
  PROTOBUF_NODISCARD std::string* release_local_address();
  void set_allocated_local_address(std::string* local_address);
  private:
  const std::string& _internal_local_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_local_address(const std::string& value);
  std::string* _internal_mutable_local_address();
  public:

  // string remote_address = 2;
  void clear_remote_address();
  const std::string& remote_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_remote_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_remote_address();
  PROTOBUF_NODISCARD std::string* release_remote_address();
  void set_allocated_remote_address(std::string* remote_address);
  private:
  const std::string& _internal_remote_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_remote_address(const std::string& value);
  std::string* _internal_mutable_remote_address();
  public:

  // int32 local_port = 3;
  void clear_local_port();
  int32_t local_port() const;
  void set_local_port(int32_t value);
  private:
  int32_t _internal_local_port() const;
  void _internal_set_local_port(int32_t value);
  public:

  // int32 remote_port = 4;
  void clear_remote_port();
  int32_t remote_port() const;
  void set_remote_port(int32_t value);
  private:
  int32_t _internal_remote_port() const;
  void _internal_set_remote_port(int32_t value);
  public:

  // uint64 sequence_number = 5;
  void clear_sequence_number();
  uint64_t sequence_number() const;
  void set_sequence_number(uint64_t value);
  private:
  uint64_t _internal_sequence_number() const;
  void _internal_set_sequence_number(uint64_t value);
  public:

  // bool flag = 6;
  void clear_flag();
  bool flag() const;
  void set_flag(bool value);
  private:
  bool _internal_flag() const;
  void _internal_set_flag(bool value);
  public:

  // @@protoc_insertion_point(class_scope:packet.TcpMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr local_address_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr remote_address_;
    int32_t local_port_;
    int32_t remote_port_;
    uint64_t sequence_number_;
    bool flag_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fanalysis_2eproto;
};
// -------------------------------------------------------------------

class AnalysisAck final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:packet.AnalysisAck) */ {
 public:
  inline AnalysisAck() : AnalysisAck(nullptr) {}
  ~AnalysisAck() override;
  explicit PROTOBUF_CONSTEXPR AnalysisAck(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AnalysisAck(const AnalysisAck& from);
  AnalysisAck(AnalysisAck&& from) noexcept
    : AnalysisAck() {
    *this = ::std::move(from);
  }

  inline AnalysisAck& operator=(const AnalysisAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnalysisAck& operator=(AnalysisAck&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AnalysisAck& default_instance() {
    return *internal_default_instance();
  }
  static inline const AnalysisAck* internal_default_instance() {
    return reinterpret_cast<const AnalysisAck*>(
               &_AnalysisAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AnalysisAck& a, AnalysisAck& b) {
    a.Swap(&b);
  }
  inline void Swap(AnalysisAck* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnalysisAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnalysisAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AnalysisAck>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AnalysisAck& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AnalysisAck& from) {
    AnalysisAck::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AnalysisAck* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "packet.AnalysisAck";
  }
  protected:
  explicit AnalysisAck(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kAcceptedFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool accepted = 1;
  void clear_accepted();
  bool accepted() const;
  void set_accepted(bool value);
  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:packet.AnalysisAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    bool accepted_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fanalysis_2eproto;
};
// -------------------------------------------------------------------

class PacketEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:packet.PacketEvent) */ {
 public:
  inline PacketEvent() : PacketEvent(nullptr) {}
  ~PacketEvent() override;
  explicit PROTOBUF_CONSTEXPR PacketEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PacketEvent(const PacketEvent& from);
  PacketEvent(PacketEvent&& from) noexcept
    : PacketEvent() {
    *this = ::std::move(from);
  }

  inline PacketEvent& operator=(const PacketEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketEvent& operator=(PacketEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PacketEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const PacketEvent* internal_default_instance() {
    return reinterpret_cast<const PacketEvent*>(
               &_PacketEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PacketEvent& a, PacketEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(PacketEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PacketEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PacketEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PacketEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PacketEvent& from) {
    PacketEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PacketEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "packet.PacketEvent";
  }
  protected:
  explicit PacketEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRemoteAddressFieldNumber = 1,
    kLocalAddressFieldNumber = 2,
    kProtocolFieldNumber = 4,
    kRemotePortFieldNumber = 3,
    kPayloadSizeFieldNumber = 6,
    kSequenceNumberFieldNumber = 5,
    kFlagFieldNumber = 7,
  };
  // string remoteAddress = 1;
  void clear_remoteaddress();
  const std::string& remoteaddress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_remoteaddress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_remoteaddress();
  PROTOBUF_NODISCARD std::string* release_remoteaddress();
  void set_allocated_remoteaddress(std::string* remoteaddress);
  private:
  const std::string& _internal_remoteaddress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_remoteaddress(const std::string& value);
  std::string* _internal_mutable_remoteaddress();
  public:

  // string localAddress = 2;
  void clear_localaddress();
  const std::string& localaddress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_localaddress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_localaddress();
  PROTOBUF_NODISCARD std::string* release_localaddress();
  void set_allocated_localaddress(std::string* localaddress);
  private:
  const std::string& _internal_localaddress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_localaddress(const std::string& value);
  std::string* _internal_mutable_localaddress();
  public:

  // string protocol = 4;
  void clear_protocol();
  const std::string& protocol() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_protocol(ArgT0&& arg0, ArgT... args);
  std::string* mutable_protocol();
  PROTOBUF_NODISCARD std::string* release_protocol();
  void set_allocated_protocol(std::string* protocol);
  private:
  const std::string& _internal_protocol() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_protocol(const std::string& value);
  std::string* _internal_mutable_protocol();
  public:

  // uint32 remotePort = 3;
  void clear_remoteport();
  uint32_t remoteport() const;
  void set_remoteport(uint32_t value);
  private:
  uint32_t _internal_remoteport() const;
  void _internal_set_remoteport(uint32_t value);
  public:

  // uint32 payloadSize = 6;
  void clear_payloadsize();
  uint32_t payloadsize() const;
  void set_payloadsize(uint32_t value);
  private:
  uint32_t _internal_payloadsize() const;
  void _internal_set_payloadsize(uint32_t value);
  public:

  // uint64 sequenceNumber = 5;
  void clear_sequencenumber();
  uint64_t sequencenumber() const;
  void set_sequencenumber(uint64_t value);
  private:
  uint64_t _internal_sequencenumber() const;
  void _internal_set_sequencenumber(uint64_t value);
  public:

  // bool flag = 7;
  void clear_flag();
  bool flag() const;
  void set_flag(bool value);
  private:
  bool _internal_flag() const;
  void _internal_set_flag(bool value);
  public:

  // @@protoc_insertion_point(class_scope:packet.PacketEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr remoteaddress_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr localaddress_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr protocol_;
    uint32_t remoteport_;
    uint32_t payloadsize_;
    uint64_t sequencenumber_;
    bool flag_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fanalysis_2eproto;
};
// -------------------------------------------------------------------

class EventBatch final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:packet.EventBatch) */ {
 public:
  inline EventBatch() : EventBatch(nullptr) {}
  ~EventBatch() override;
  explicit PROTOBUF_CONSTEXPR EventBatch(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EventBatch(const EventBatch& from);
  EventBatch(EventBatch&& from) noexcept
    : EventBatch() {
    *this = ::std::move(from);
  }

  inline EventBatch& operator=(const EventBatch& from) {
    CopyFrom(from);
    return *this;
  }
  inline EventBatch& operator=(EventBatch&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EventBatch& default_instance() {
    return *internal_default_instance();
  }
  static inline const EventBatch* internal_default_instance() {
    return reinterpret_cast<const EventBatch*>(
               &_EventBatch_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(EventBatch& a, EventBatch& b) {
    a.Swap(&b);
  }
  inline void Swap(EventBatch* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EventBatch* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EventBatch* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EventBatch>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EventBatch& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EventBatch& from) {
    EventBatch::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EventBatch* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "packet.EventBatch";
  }
  protected:
  explicit EventBatch(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventsFieldNumber = 1,
  };
  // repeated .packet.PacketEvent events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;
  public:
  void clear_events();
  ::packet::PacketEvent* mutable_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::PacketEvent >*
      mutable_events();
  private:
  const ::packet::PacketEvent& _internal_events(int index) const;
  ::packet::PacketEvent* _internal_add_events();
  public:
  const ::packet::PacketEvent& events(int index) const;
  ::packet::PacketEvent* add_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::PacketEvent >&
      events() const;

  // @@protoc_insertion_point(class_scope:packet.EventBatch)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::PacketEvent > events_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fanalysis_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PacketWindow

// int64 window_start = 1;
inline void PacketWindow::clear_window_start() {
  _impl_.window_start_ = int64_t{0};
}
inline int64_t PacketWindow::_internal_window_start() const {
  return _impl_.window_start_;
}
inline int64_t PacketWindow::window_start() const {
  // @@protoc_insertion_point(field_get:packet.PacketWindow.window_start)
  return _internal_window_start();
}
inline void PacketWindow::_internal_set_window_start(int64_t value) {
  
  _impl_.window_start_ = value;
}
inline void PacketWindow::set_window_start(int64_t value) {
  _internal_set_window_start(value);
  // @@protoc_insertion_point(field_set:packet.PacketWindow.window_start)
}

// int64 window_end = 2;
inline void PacketWindow::clear_window_end() {
  _impl_.window_end_ = int64_t{0};
}
inline int64_t PacketWindow::_internal_window_end() const {
  return _impl_.window_end_;
}
inline int64_t PacketWindow::window_end() const {
  // @@protoc_insertion_point(field_get:packet.PacketWindow.window_end)
  return _internal_window_end();
}
inline void PacketWindow::_internal_set_window_end(int64_t value) {
  
  _impl_.window_end_ = value;
}
inline void PacketWindow::set_window_end(int64_t value) {
  _internal_set_window_end(value);
  // @@protoc_insertion_point(field_set:packet.PacketWindow.window_end)
}

// int64 user_id = 3;
inline void PacketWindow::clear_user_id() {
  _impl_.user_id_ = int64_t{0};
}
inline int64_t PacketWindow::_internal_user_id() const {
  return _impl_.user_id_;
}
inline int64_t PacketWindow::user_id() const {
  // @@protoc_insertion_point(field_get:packet.PacketWindow.user_id)
  return _internal_user_id();
}
inline void PacketWindow::_internal_set_user_id(int64_t value) {
  
  _impl_.user_id_ = value;
}
inline void PacketWindow::set_user_id(int64_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:packet.PacketWindow.user_id)
}

// repeated .packet.HttpSession http_sessions = 4;
inline int PacketWindow::_internal_http_sessions_size() const {
  return _impl_.http_sessions_.size();
}
inline int PacketWindow::http_sessions_size() const {
  return _internal_http_sessions_size();
}
inline void PacketWindow::clear_http_sessions() {
  _impl_.http_sessions_.Clear();
}
inline ::packet::HttpSession* PacketWindow::mutable_http_sessions(int index) {
  // @@protoc_insertion_point(field_mutable:packet.PacketWindow.http_sessions)
  return _impl_.http_sessions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::HttpSession >*
PacketWindow::mutable_http_sessions() {
  // @@protoc_insertion_point(field_mutable_list:packet.PacketWindow.http_sessions)
  return &_impl_.http_sessions_;
}
inline const ::packet::HttpSession& PacketWindow::_internal_http_sessions(int index) const {
  return _impl_.http_sessions_.Get(index);
}
inline const ::packet::HttpSession& PacketWindow::http_sessions(int index) const {
  // @@protoc_insertion_point(field_get:packet.PacketWindow.http_sessions)
  return _internal_http_sessions(index);
}
inline ::packet::HttpSession* PacketWindow::_internal_add_http_sessions() {
  return _impl_.http_sessions_.Add();
}
inline ::packet::HttpSession* PacketWindow::add_http_sessions() {
  ::packet::HttpSession* _add = _internal_add_http_sessions();
  // @@protoc_insertion_point(field_add:packet.PacketWindow.http_sessions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::HttpSession >&
PacketWindow::http_sessions() const {
  // @@protoc_insertion_point(field_list:packet.PacketWindow.http_sessions)
  return _impl_.http_sessions_;
}

// -------------------------------------------------------------------

// HttpSession

// string method = 1;
inline void HttpSession::clear_method() {
  _impl_.method_.ClearToEmpty();
}
inline const std::string& HttpSession::method() const {
  // @@protoc_insertion_point(field_get:packet.HttpSession.method)
  return _internal_method();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HttpSession::set_method(ArgT0&& arg0, ArgT... args) {
 
 _impl_.method_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.HttpSession.method)
}
inline std::string* HttpSession::mutable_method() {
  std::string* _s = _internal_mutable_method();
  // @@protoc_insertion_point(field_mutable:packet.HttpSession.method)
  return _s;
}
inline const std::string& HttpSession::_internal_method() const {
  return _impl_.method_.Get();
}
inline void HttpSession::_internal_set_method(const std::string& value) {
  
  _impl_.method_.Set(value, GetArenaForAllocation());
}
inline std::string* HttpSession::_internal_mutable_method() {
  
  return _impl_.method_.Mutable(GetArenaForAllocation());
}
inline std::string* HttpSession::release_method() {
  // @@protoc_insertion_point(field_release:packet.HttpSession.method)
  return _impl_.method_.Release();
}
inline void HttpSession::set_allocated_method(std::string* method) {
  if (method != nullptr) {
    
  } else {
    
  }
  _impl_.method_.SetAllocated(method, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.method_.IsDefault()) {
    _impl_.method_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.HttpSession.method)
}

// string protocol = 2;
inline void HttpSession::clear_protocol() {
  _impl_.protocol_.ClearToEmpty();
}
inline const std::string& HttpSession::protocol() const {
  // @@protoc_insertion_point(field_get:packet.HttpSession.protocol)
  return _internal_protocol();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HttpSession::set_protocol(ArgT0&& arg0, ArgT... args) {
 
 _impl_.protocol_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.HttpSession.protocol)
}
inline std::string* HttpSession::mutable_protocol() {
  std::string* _s = _internal_mutable_protocol();
  // @@protoc_insertion_point(field_mutable:packet.HttpSession.protocol)
  return _s;
}
inline const std::string& HttpSession::_internal_protocol() const {
  return _impl_.protocol_.Get();
}
inline void HttpSession::_internal_set_protocol(const std::string& value) {
  
  _impl_.protocol_.Set(value, GetArenaForAllocation());
}
inline std::string* HttpSession::_internal_mutable_protocol() {
  
  return _impl_.protocol_.Mutable(GetArenaForAllocation());
}
inline std::string* HttpSession::release_protocol() {
  // @@protoc_insertion_point(field_release:packet.HttpSession.protocol)
  return _impl_.protocol_.Release();
}
inline void HttpSession::set_allocated_protocol(std::string* protocol) {
  if (protocol != nullptr) {
    
  } else {
    
  }
  _impl_.protocol_.SetAllocated(protocol, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.protocol_.IsDefault()) {
    _impl_.protocol_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.HttpSession.protocol)
}

// string uri = 3;
inline void HttpSession::clear_uri() {
  _impl_.uri_.ClearToEmpty();
}
inline const std::string& HttpSession::uri() const {
  // @@protoc_insertion_point(field_get:packet.HttpSession.uri)
  return _internal_uri();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void HttpSession::set_uri(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uri_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.HttpSession.uri)
}
inline std::string* HttpSession::mutable_uri() {
  std::string* _s = _internal_mutable_uri();
  // @@protoc_insertion_point(field_mutable:packet.HttpSession.uri)
  return _s;
}
inline const std::string& HttpSession::_internal_uri() const {
  return _impl_.uri_.Get();
}
inline void HttpSession::_internal_set_uri(const std::string& value) {
  
  _impl_.uri_.Set(value, GetArenaForAllocation());
}
inline std::string* HttpSession::_internal_mutable_uri() {
  
  return _impl_.uri_.Mutable(GetArenaForAllocation());
}
inline std::string* HttpSession::release_uri() {
  // @@protoc_insertion_point(field_release:packet.HttpSession.uri)
  return _impl_.uri_.Release();
}
inline void HttpSession::set_allocated_uri(std::string* uri) {
  if (uri != nullptr) {
    
  } else {
    
  }
  _impl_.uri_.SetAllocated(uri, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uri_.IsDefault()) {
    _impl_.uri_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.HttpSession.uri)
}

// repeated .packet.TcpMeta tcp_packets = 4;
inline int HttpSession::_internal_tcp_packets_size() const {
  return _impl_.tcp_packets_.size();
}
inline int HttpSession::tcp_packets_size() const {
  return _internal_tcp_packets_size();
}
inline void HttpSession::clear_tcp_packets() {
  _impl_.tcp_packets_.Clear();
}
inline ::packet::TcpMeta* HttpSession::mutable_tcp_packets(int index) {
  // @@protoc_insertion_point(field_mutable:packet.HttpSession.tcp_packets)
  return _impl_.tcp_packets_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::TcpMeta >*
HttpSession::mutable_tcp_packets() {
  // @@protoc_insertion_point(field_mutable_list:packet.HttpSession.tcp_packets)
  return &_impl_.tcp_packets_;
}
inline const ::packet::TcpMeta& HttpSession::_internal_tcp_packets(int index) const {
  return _impl_.tcp_packets_.Get(index);
}
inline const ::packet::TcpMeta& HttpSession::tcp_packets(int index) const {
  // @@protoc_insertion_point(field_get:packet.HttpSession.tcp_packets)
  return _internal_tcp_packets(index);
}
inline ::packet::TcpMeta* HttpSession::_internal_add_tcp_packets() {
  return _impl_.tcp_packets_.Add();
}
inline ::packet::TcpMeta* HttpSession::add_tcp_packets() {
  ::packet::TcpMeta* _add = _internal_add_tcp_packets();
  // @@protoc_insertion_point(field_add:packet.HttpSession.tcp_packets)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::TcpMeta >&
HttpSession::tcp_packets() const {
  // @@protoc_insertion_point(field_list:packet.HttpSession.tcp_packets)
  return _impl_.tcp_packets_;
}

// -------------------------------------------------------------------

// TcpMeta

// string local_address = 1;
inline void TcpMeta::clear_local_address() {
  _impl_.local_address_.ClearToEmpty();
}
inline const std::string& TcpMeta::local_address() const {
  // @@protoc_insertion_point(field_get:packet.TcpMeta.local_address)
  return _internal_local_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TcpMeta::set_local_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.local_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.TcpMeta.local_address)
}
inline std::string* TcpMeta::mutable_local_address() {
  std::string* _s = _internal_mutable_local_address();
  // @@protoc_insertion_point(field_mutable:packet.TcpMeta.local_address)
  return _s;
}
inline const std::string& TcpMeta::_internal_local_address() const {
  return _impl_.local_address_.Get();
}
inline void TcpMeta::_internal_set_local_address(const std::string& value) {
  
  _impl_.local_address_.Set(value, GetArenaForAllocation());
}
inline std::string* TcpMeta::_internal_mutable_local_address() {
  
  return _impl_.local_address_.Mutable(GetArenaForAllocation());
}
inline std::string* TcpMeta::release_local_address() {
  // @@protoc_insertion_point(field_release:packet.TcpMeta.local_address)
  return _impl_.local_address_.Release();
}
inline void TcpMeta::set_allocated_local_address(std::string* local_address) {
  if (local_address != nullptr) {
    
  } else {
    
  }
  _impl_.local_address_.SetAllocated(local_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.local_address_.IsDefault()) {
    _impl_.local_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.TcpMeta.local_address)
}

// string remote_address = 2;
inline void TcpMeta::clear_remote_address() {
  _impl_.remote_address_.ClearToEmpty();
}
inline const std::string& TcpMeta::remote_address() const {
  // @@protoc_insertion_point(field_get:packet.TcpMeta.remote_address)
  return _internal_remote_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TcpMeta::set_remote_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.remote_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.TcpMeta.remote_address)
}
inline std::string* TcpMeta::mutable_remote_address() {
  std::string* _s = _internal_mutable_remote_address();
  // @@protoc_insertion_point(field_mutable:packet.TcpMeta.remote_address)
  return _s;
}
inline const std::string& TcpMeta::_internal_remote_address() const {
  return _impl_.remote_address_.Get();
}
inline void TcpMeta::_internal_set_remote_address(const std::string& value) {
  
  _impl_.remote_address_.Set(value, GetArenaForAllocation());
}
inline std::string* TcpMeta::_internal_mutable_remote_address() {
  
  return _impl_.remote_address_.Mutable(GetArenaForAllocation());
}
inline std::string* TcpMeta::release_remote_address() {
  // @@protoc_insertion_point(field_release:packet.TcpMeta.remote_address)
  return _impl_.remote_address_.Release();
}
inline void TcpMeta::set_allocated_remote_address(std::string* remote_address) {
  if (remote_address != nullptr) {
    
  } else {
    
  }
  _impl_.remote_address_.SetAllocated(remote_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.remote_address_.IsDefault()) {
    _impl_.remote_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.TcpMeta.remote_address)
}

// int32 local_port = 3;
inline void TcpMeta::clear_local_port() {
  _impl_.local_port_ = 0;
}
inline int32_t TcpMeta::_internal_local_port() const {
  return _impl_.local_port_;
}
inline int32_t TcpMeta::local_port() const {
  // @@protoc_insertion_point(field_get:packet.TcpMeta.local_port)
  return _internal_local_port();
}
inline void TcpMeta::_internal_set_local_port(int32_t value) {
  
  _impl_.local_port_ = value;
}
inline void TcpMeta::set_local_port(int32_t value) {
  _internal_set_local_port(value);
  // @@protoc_insertion_point(field_set:packet.TcpMeta.local_port)
}

// int32 remote_port = 4;
inline void TcpMeta::clear_remote_port() {
  _impl_.remote_port_ = 0;
}
inline int32_t TcpMeta::_internal_remote_port() const {
  return _impl_.remote_port_;
}
inline int32_t TcpMeta::remote_port() const {
  // @@protoc_insertion_point(field_get:packet.TcpMeta.remote_port)
  return _internal_remote_port();
}
inline void TcpMeta::_internal_set_remote_port(int32_t value) {
  
  _impl_.remote_port_ = value;
}
inline void TcpMeta::set_remote_port(int32_t value) {
  _internal_set_remote_port(value);
  // @@protoc_insertion_point(field_set:packet.TcpMeta.remote_port)
}

// uint64 sequence_number = 5;
inline void TcpMeta::clear_sequence_number() {
  _impl_.sequence_number_ = uint64_t{0u};
}
inline uint64_t TcpMeta::_internal_sequence_number() const {
  return _impl_.sequence_number_;
}
inline uint64_t TcpMeta::sequence_number() const {
  // @@protoc_insertion_point(field_get:packet.TcpMeta.sequence_number)
  return _internal_sequence_number();
}
inline void TcpMeta::_internal_set_sequence_number(uint64_t value) {
  
  _impl_.sequence_number_ = value;
}
inline void TcpMeta::set_sequence_number(uint64_t value) {
  _internal_set_sequence_number(value);
  // @@protoc_insertion_point(field_set:packet.TcpMeta.sequence_number)
}

// bool flag = 6;
inline void TcpMeta::clear_flag() {
  _impl_.flag_ = false;
}
inline bool TcpMeta::_internal_flag() const {
  return _impl_.flag_;
}
inline bool TcpMeta::flag() const {
  // @@protoc_insertion_point(field_get:packet.TcpMeta.flag)
  return _internal_flag();
}
inline void TcpMeta::_internal_set_flag(bool value) {
  
  _impl_.flag_ = value;
}
inline void TcpMeta::set_flag(bool value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:packet.TcpMeta.flag)
}

// -------------------------------------------------------------------

// AnalysisAck

// bool accepted = 1;
inline void AnalysisAck::clear_accepted() {
  _impl_.accepted_ = false;
}
inline bool AnalysisAck::_internal_accepted() const {
  return _impl_.accepted_;
}
inline bool AnalysisAck::accepted() const {
  // @@protoc_insertion_point(field_get:packet.AnalysisAck.accepted)
  return _internal_accepted();
}
inline void AnalysisAck::_internal_set_accepted(bool value) {
  
  _impl_.accepted_ = value;
}
inline void AnalysisAck::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:packet.AnalysisAck.accepted)
}

// string message = 2;
inline void AnalysisAck::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& AnalysisAck::message() const {
  // @@protoc_insertion_point(field_get:packet.AnalysisAck.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AnalysisAck::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.AnalysisAck.message)
}
inline std::string* AnalysisAck::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:packet.AnalysisAck.message)
  return _s;
}
inline const std::string& AnalysisAck::_internal_message() const {
  return _impl_.message_.Get();
}
inline void AnalysisAck::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* AnalysisAck::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* AnalysisAck::release_message() {
  // @@protoc_insertion_point(field_release:packet.AnalysisAck.message)
  return _impl_.message_.Release();
}
inline void AnalysisAck::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.AnalysisAck.message)
}

// -------------------------------------------------------------------

// PacketEvent

// string remoteAddress = 1;
inline void PacketEvent::clear_remoteaddress() {
  _impl_.remoteaddress_.ClearToEmpty();
}
inline const std::string& PacketEvent::remoteaddress() const {
  // @@protoc_insertion_point(field_get:packet.PacketEvent.remoteAddress)
  return _internal_remoteaddress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PacketEvent::set_remoteaddress(ArgT0&& arg0, ArgT... args) {
 
 _impl_.remoteaddress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.PacketEvent.remoteAddress)
}
inline std::string* PacketEvent::mutable_remoteaddress() {
  std::string* _s = _internal_mutable_remoteaddress();
  // @@protoc_insertion_point(field_mutable:packet.PacketEvent.remoteAddress)
  return _s;
}
inline const std::string& PacketEvent::_internal_remoteaddress() const {
  return _impl_.remoteaddress_.Get();
}
inline void PacketEvent::_internal_set_remoteaddress(const std::string& value) {
  
  _impl_.remoteaddress_.Set(value, GetArenaForAllocation());
}
inline std::string* PacketEvent::_internal_mutable_remoteaddress() {
  
  return _impl_.remoteaddress_.Mutable(GetArenaForAllocation());
}
inline std::string* PacketEvent::release_remoteaddress() {
  // @@protoc_insertion_point(field_release:packet.PacketEvent.remoteAddress)
  return _impl_.remoteaddress_.Release();
}
inline void PacketEvent::set_allocated_remoteaddress(std::string* remoteaddress) {
  if (remoteaddress != nullptr) {
    
  } else {
    
  }
  _impl_.remoteaddress_.SetAllocated(remoteaddress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.remoteaddress_.IsDefault()) {
    _impl_.remoteaddress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.PacketEvent.remoteAddress)
}

// string localAddress = 2;
inline void PacketEvent::clear_localaddress() {
  _impl_.localaddress_.ClearToEmpty();
}
inline const std::string& PacketEvent::localaddress() const {
  // @@protoc_insertion_point(field_get:packet.PacketEvent.localAddress)
  return _internal_localaddress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PacketEvent::set_localaddress(ArgT0&& arg0, ArgT... args) {
 
 _impl_.localaddress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.PacketEvent.localAddress)
}
inline std::string* PacketEvent::mutable_localaddress() {
  std::string* _s = _internal_mutable_localaddress();
  // @@protoc_insertion_point(field_mutable:packet.PacketEvent.localAddress)
  return _s;
}
inline const std::string& PacketEvent::_internal_localaddress() const {
  return _impl_.localaddress_.Get();
}
inline void PacketEvent::_internal_set_localaddress(const std::string& value) {
  
  _impl_.localaddress_.Set(value, GetArenaForAllocation());
}
inline std::string* PacketEvent::_internal_mutable_localaddress() {
  
  return _impl_.localaddress_.Mutable(GetArenaForAllocation());
}
inline std::string* PacketEvent::release_localaddress() {
  // @@protoc_insertion_point(field_release:packet.PacketEvent.localAddress)
  return _impl_.localaddress_.Release();
}
inline void PacketEvent::set_allocated_localaddress(std::string* localaddress) {
  if (localaddress != nullptr) {
    
  } else {
    
  }
  _impl_.localaddress_.SetAllocated(localaddress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.localaddress_.IsDefault()) {
    _impl_.localaddress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.PacketEvent.localAddress)
}

// uint32 remotePort = 3;
inline void PacketEvent::clear_remoteport() {
  _impl_.remoteport_ = 0u;
}
inline uint32_t PacketEvent::_internal_remoteport() const {
  return _impl_.remoteport_;
}
inline uint32_t PacketEvent::remoteport() const {
  // @@protoc_insertion_point(field_get:packet.PacketEvent.remotePort)
  return _internal_remoteport();
}
inline void PacketEvent::_internal_set_remoteport(uint32_t value) {
  
  _impl_.remoteport_ = value;
}
inline void PacketEvent::set_remoteport(uint32_t value) {
  _internal_set_remoteport(value);
  // @@protoc_insertion_point(field_set:packet.PacketEvent.remotePort)
}

// string protocol = 4;
inline void PacketEvent::clear_protocol() {
  _impl_.protocol_.ClearToEmpty();
}
inline const std::string& PacketEvent::protocol() const {
  // @@protoc_insertion_point(field_get:packet.PacketEvent.protocol)
  return _internal_protocol();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PacketEvent::set_protocol(ArgT0&& arg0, ArgT... args) {
 
 _impl_.protocol_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:packet.PacketEvent.protocol)
}
inline std::string* PacketEvent::mutable_protocol() {
  std::string* _s = _internal_mutable_protocol();
  // @@protoc_insertion_point(field_mutable:packet.PacketEvent.protocol)
  return _s;
}
inline const std::string& PacketEvent::_internal_protocol() const {
  return _impl_.protocol_.Get();
}
inline void PacketEvent::_internal_set_protocol(const std::string& value) {
  
  _impl_.protocol_.Set(value, GetArenaForAllocation());
}
inline std::string* PacketEvent::_internal_mutable_protocol() {
  
  return _impl_.protocol_.Mutable(GetArenaForAllocation());
}
inline std::string* PacketEvent::release_protocol() {
  // @@protoc_insertion_point(field_release:packet.PacketEvent.protocol)
  return _impl_.protocol_.Release();
}
inline void PacketEvent::set_allocated_protocol(std::string* protocol) {
  if (protocol != nullptr) {
    
  } else {
    
  }
  _impl_.protocol_.SetAllocated(protocol, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.protocol_.IsDefault()) {
    _impl_.protocol_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:packet.PacketEvent.protocol)
}

// uint64 sequenceNumber = 5;
inline void PacketEvent::clear_sequencenumber() {
  _impl_.sequencenumber_ = uint64_t{0u};
}
inline uint64_t PacketEvent::_internal_sequencenumber() const {
  return _impl_.sequencenumber_;
}
inline uint64_t PacketEvent::sequencenumber() const {
  // @@protoc_insertion_point(field_get:packet.PacketEvent.sequenceNumber)
  return _internal_sequencenumber();
}
inline void PacketEvent::_internal_set_sequencenumber(uint64_t value) {
  
  _impl_.sequencenumber_ = value;
}
inline void PacketEvent::set_sequencenumber(uint64_t value) {
  _internal_set_sequencenumber(value);
  // @@protoc_insertion_point(field_set:packet.PacketEvent.sequenceNumber)
}

// uint32 payloadSize = 6;
inline void PacketEvent::clear_payloadsize() {
  _impl_.payloadsize_ = 0u;
}
inline uint32_t PacketEvent::_internal_payloadsize() const {
  return _impl_.payloadsize_;
}
inline uint32_t PacketEvent::payloadsize() const {
  // @@protoc_insertion_point(field_get:packet.PacketEvent.payloadSize)
  return _internal_payloadsize();
}
inline void PacketEvent::_internal_set_payloadsize(uint32_t value) {
  
  _impl_.payloadsize_ = value;
}
inline void PacketEvent::set_payloadsize(uint32_t value) {
  _internal_set_payloadsize(value);
  // @@protoc_insertion_point(field_set:packet.PacketEvent.payloadSize)
}

// bool flag = 7;
inline void PacketEvent::clear_flag() {
  _impl_.flag_ = false;
}
inline bool PacketEvent::_internal_flag() const {
  return _impl_.flag_;
}
inline bool PacketEvent::flag() const {
  // @@protoc_insertion_point(field_get:packet.PacketEvent.flag)
  return _internal_flag();
}
inline void PacketEvent::_internal_set_flag(bool value) {
  
  _impl_.flag_ = value;
}
inline void PacketEvent::set_flag(bool value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:packet.PacketEvent.flag)
}

// -------------------------------------------------------------------

// EventBatch

// repeated .packet.PacketEvent events = 1;
inline int EventBatch::_internal_events_size() const {
  return _impl_.events_.size();
}
inline int EventBatch::events_size() const {
  return _internal_events_size();
}
inline void EventBatch::clear_events() {
  _impl_.events_.Clear();
}
inline ::packet::PacketEvent* EventBatch::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:packet.EventBatch.events)
  return _impl_.events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::PacketEvent >*
EventBatch::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:packet.EventBatch.events)
  return &_impl_.events_;
}
inline const ::packet::PacketEvent& EventBatch::_internal_events(int index) const {
  return _impl_.events_.Get(index);
}
inline const ::packet::PacketEvent& EventBatch::events(int index) const {
  // @@protoc_insertion_point(field_get:packet.EventBatch.events)
  return _internal_events(index);
}
inline ::packet::PacketEvent* EventBatch::_internal_add_events() {
  return _impl_.events_.Add();
}
inline ::packet::PacketEvent* EventBatch::add_events() {
  ::packet::PacketEvent* _add = _internal_add_events();
  // @@protoc_insertion_point(field_add:packet.EventBatch.events)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::packet::PacketEvent >&
EventBatch::events() const {
  // @@protoc_insertion_point(field_list:packet.EventBatch.events)
  return _impl_.events_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace packet

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_packet_5fanalysis_2eproto
