// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: packet_analysis.proto

#include "packet_analysis.pb.h"
#include "packet_analysis.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace packet {

static const char* PacketAnalysisService_method_names[] = {
  "/packet.PacketAnalysisService/StreamWindow",
};

std::unique_ptr< PacketAnalysisService::Stub> PacketAnalysisService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PacketAnalysisService::Stub> stub(new PacketAnalysisService::Stub(channel, options));
  return stub;
}

PacketAnalysisService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamWindow_(PacketAnalysisService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::packet::PacketWindow>* PacketAnalysisService::Stub::StreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response) {
  return ::grpc::internal::ClientWriterFactory< ::packet::PacketWindow>::Create(channel_.get(), rpcmethod_StreamWindow_, context, response);
}

void PacketAnalysisService::Stub::async::StreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::ClientWriteReactor< ::packet::PacketWindow>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::packet::PacketWindow>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamWindow_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::packet::PacketWindow>* PacketAnalysisService::Stub::AsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::packet::PacketWindow>::Create(channel_.get(), cq, rpcmethod_StreamWindow_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::packet::PacketWindow>* PacketAnalysisService::Stub::PrepareAsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::packet::PacketWindow>::Create(channel_.get(), cq, rpcmethod_StreamWindow_, context, response, false, nullptr);
}

PacketAnalysisService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PacketAnalysisService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< PacketAnalysisService::Service, ::packet::PacketWindow, ::packet::AnalysisAck>(
          [](PacketAnalysisService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::packet::PacketWindow>* reader,
             ::packet::AnalysisAck* resp) {
               return service->StreamWindow(ctx, reader, resp);
             }, this)));
}

PacketAnalysisService::Service::~Service() {
}

::grpc::Status PacketAnalysisService::Service::StreamWindow(::grpc::ServerContext* context, ::grpc::ServerReader< ::packet::PacketWindow>* reader, ::packet::AnalysisAck* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace packet

