// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: packet_analysis.proto

#include "packet_analysis.pb.h"
#include "packet_analysis.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace packet {

static const char* PacketAnalysisService_method_names[] = {
  "/packet.PacketAnalysisService/StreamWindow",
};

std::unique_ptr< PacketAnalysisService::Stub> PacketAnalysisService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PacketAnalysisService::Stub> stub(new PacketAnalysisService::Stub(channel, options));
  return stub;
}

PacketAnalysisService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamWindow_(PacketAnalysisService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::packet::PacketWindow>* PacketAnalysisService::Stub::StreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response) {
  return ::grpc::internal::ClientWriterFactory< ::packet::PacketWindow>::Create(channel_.get(), rpcmethod_StreamWindow_, context, response);
}

void PacketAnalysisService::Stub::async::StreamWindow(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::ClientWriteReactor< ::packet::PacketWindow>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::packet::PacketWindow>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamWindow_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::packet::PacketWindow>* PacketAnalysisService::Stub::AsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::packet::PacketWindow>::Create(channel_.get(), cq, rpcmethod_StreamWindow_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::packet::PacketWindow>* PacketAnalysisService::Stub::PrepareAsyncStreamWindowRaw(::grpc::ClientContext* context, ::packet::AnalysisAck* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::packet::PacketWindow>::Create(channel_.get(), cq, rpcmethod_StreamWindow_, context, response, false, nullptr);
}

PacketAnalysisService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PacketAnalysisService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< PacketAnalysisService::Service, ::packet::PacketWindow, ::packet::AnalysisAck>(
          [](PacketAnalysisService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::packet::PacketWindow>* reader,
             ::packet::AnalysisAck* resp) {
               return service->StreamWindow(ctx, reader, resp);
             }, this)));
}

PacketAnalysisService::Service::~Service() {
}

::grpc::Status PacketAnalysisService::Service::StreamWindow(::grpc::ServerContext* context, ::grpc::ServerReader< ::packet::PacketWindow>* reader, ::packet::AnalysisAck* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* PacketAnalyzer_method_names[] = {
  "/packet.PacketAnalyzer/GetEvents",
};

std::unique_ptr< PacketAnalyzer::Stub> PacketAnalyzer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PacketAnalyzer::Stub> stub(new PacketAnalyzer::Stub(channel, options));
  return stub;
}

PacketAnalyzer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetEvents_(PacketAnalyzer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PacketAnalyzer::Stub::GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::packet::EventBatch* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::packet::EventBatch, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetEvents_, context, request, response);
}

void PacketAnalyzer::Stub::async::GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::packet::EventBatch, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEvents_, context, request, response, std::move(f));
}

void PacketAnalyzer::Stub::async::GetEvents(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetEvents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::packet::EventBatch>* PacketAnalyzer::Stub::PrepareAsyncGetEventsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::packet::EventBatch, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetEvents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::packet::EventBatch>* PacketAnalyzer::Stub::AsyncGetEventsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetEventsRaw(context, request, cq);
  result->StartCall();
  return result;
}

PacketAnalyzer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PacketAnalyzer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PacketAnalyzer::Service, ::google::protobuf::Empty, ::packet::EventBatch, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PacketAnalyzer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::packet::EventBatch* resp) {
               return service->GetEvents(ctx, req, resp);
             }, this)));
}

PacketAnalyzer::Service::~Service() {
}

::grpc::Status PacketAnalyzer::Service::GetEvents(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::packet::EventBatch* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace packet

